import '@/styles/globals.css'
import { Navbar } from '@/components/navbar/page';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Footer } from '@/components/footer/page';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} main-background`}>
        <main className='overflow-x-hidden overflow-y-auto w-full h-full'>
          <Navbar />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  )
}
